name: deepttc-clean
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - chardet=5.2.0=py312h7900ff3_2
  - contourpy=1.3.0=py312h68727a3_2
  - cuda-cudart=12.4.99=hd3aeb46_0
  - cuda-cudart_linux-64=12.4.99=h59595ed_0
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.0=ha770c72_0
  - cuda-nvrtc=12.4.99=hd3aeb46_0
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.99=h59595ed_0
  - cuda-runtime=12.4.0=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h66e93f0_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h7201bc8_2
  - greenlet=3.1.1=py312h2ec8cdc_0
  - icu=75.1=he02047a_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.86.0=hb8260a3_2
  - libboost-python=1.86.0=py312hc39e661_2
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.2.65=hd3aeb46_0
  - libcufft=11.2.0.44=hd3aeb46_0
  - libcufile=1.9.0.20=hd3aeb46_0
  - libcurand=10.3.5.119=hd3aeb46_0
  - libcusolver=11.6.0.99=hd3aeb46_0
  - libcusparse=12.3.0.142=hd3aeb46_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.82.1=h2ff4ddf_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=12.2.5.2=hd3aeb46_0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.4.99=hd3aeb46_0
  - libnvjitlink=12.4.99=hd3aeb46_0
  - libnvjpeg=12.3.1.89=h59595ed_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.4=h2d7952a_2
  - librdkit=2024.09.1=h84b0b3c_1
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.5=py312h66e93f0_1
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - networkx=3.3=pyhd8ed1ab_1
  - numpy=2.1.1=py312h58c1407_0
  - ocl-icd=2.3.2=hd590300_1
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - pcre2=10.44=hba22ea6_2
  - pillow=10.4.0=py312h56024de_1
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - prettytable=3.11.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pubchempy=1.0.4=pyh864c0ab_2
  - pycairo=1.27.0=py312h51b637d_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - python=3.12.6=hc5c86c4_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - qhull=2020.2=h434a139_5
  - rdkit=2024.09.1=py312hd3b4007_1
  - readline=8.2=h8228510_1
  - reportlab=4.2.5=py312h66e93f0_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.35=py312h66e93f0_0
  - sympy=1.13.3=pypyh2585a3b_103
  - tk=8.6.13=noxft_h4845f30_101
  - torchtriton=3.0.0=py312
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
